#Spring Config
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  redis:
    host: 192.168.127.134
    port: 6379
    password: foobared
#server config
server:
  port: 9301
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

#zuul config
zuul:
  ratelimit:
    enabled: true
    key-prefix: your-prefix
    repository: REDIS
    default-policy-list: #optional - will apply unless specific policy exists
    - limit: 10 #optional - request number limit per refresh interval window
      quota: 1000 #optional - request time limit per refresh interval window (in seconds)
      refresh-interval: 60 #default value (in seconds)
  routes:
    metric-api:
      path: /api/**
      url: pay-metric-api
    metric-web:
      path: /web/**
      url: pay-metric-web
